### ISSUE TITLE
季度報告的股票營利排行榜 本益比算式BUG

### ISSUE THREAD

**Issue by vios10009** [mrbigmouth/acgn-stock#101]
排名沒問題，但本益比的算式是相反的。

像是第一位的汐宮栞，顯示的本益比是7.396，實際上是2.90。

本益比公式：每股市價/EPS

**Comment by mrbigmouth** [comment]
這裡用的公式是每股的預計分紅除以平均成交價，
如果本益比這個稱呼會讓你困惑，請提供更好的名稱。

**Comment by vios10009** [comment]
益本比，然後是否能在新增一個本益比欄位？

2017年9月23日 下午11:29，"mrbigmouth" <notifications@github.com>寫道：

**Comment by vios10009** [comment]
算式只是相反而已。

2017年9月23日 下午11:29，"mrbigmouth" <notifications@github.com>寫道：

**Comment by mrbigmouth** [comment]
63174a8f174ee784dbc33940494a6bd68b98cf23
下次維護後更新。
至於新增欄位的問題，由於已經過去的數據無法再次取得，所以可能要等下個賽季伺服器重置之後才有可能了。

**Comment by vios10009** [comment]
可以用益本比算出本益比

1/益本比=本益比

2017年9月24日 上午12:12，"mrbigmouth" <notifications@github.com>寫道：

**Comment by mrbigmouth** [comment]
欄位好像不夠塞，多加一個欄位的話狹小螢幕下會變的太擠。

**Comment by vios10009** [comment]
我覺得手機板就算沒塞，以目前的資料來看，依然是擠到無法觀看資訊的，相對於用電腦觀看之下，可以發現有很多空間。

這可能要把手機板的季度報告做改善，而不是欄位夠不夠塞，因為本身就是爆滿的狀態了。



​

2017-09-25 21:00 GMT+08:00 mrbigmouth <notifications@github.com>:
