### ISSUE TITLE
首頁無限重整

### ISSUE THREAD

**Issue by wai0806** [mrbigmouth/acgn-stock#102]
登入頁面無限重整 根本無法使用

**Comment by mrbigmouth** [comment]
觀察後無此情形，是否有更進一步的訊息能夠提供？

**Comment by wai0806** [comment]
https://drive.google.com/file/d/0Bw4ICOgLl158UHlxMFpSdFJzQkU/view
如同這個影片

**Comment by mrbigmouth** [comment]
試著打開瀏覽器的主控台console再錄一次?
話說,  有用無痕模式試過嗎?  如果無痕模式可以,  清除所有快取後再試一次.

**Comment by orcapen** [comment]
無限重整+1

**Comment by mrbigmouth** [comment]
所以有開無痕模式時依然無限重整的人嗎？
或有人能提供主控臺錯誤訊息的嗎？
