### ISSUE TITLE
未登入天數計算問題

### ISSUE THREAD

**Issue by lamlam77777** [mrbigmouth/acgn-stock#103]
使用者「lamlam77777」的帳號資訊：
帳號啟動日期：2017/09/19 13:46:57
上次登入時間：2017/09/25 03:21:18
本季度未登入天數：8

這看起來很有問題
啟動到現在都還未有8天那來的8天沒登入
還有課稅還收足7天殭屍稅
即表示系統當我一星期完全沒登入過
但理解上至少啟動那天有登錄不會7天沒登入吧

**Comment by mrbigmouth** [comment]
測不出Bug，推估是多執行緒環境下產生的問題。
暫時先對多執行緒的管理進行優化，並在今晚更新時將所有人的本季未登入時間歸零，
還有發生問題的話請再回報。

**Comment by lamlam77777** [comment]
但收稅那邊殭屍稅還是當我7000了

**Comment by lamlam77777** [comment]
還有個問題
未登入天數是有重設
但是距離上次發薪24小時後都沒發薪

**Comment by mrbigmouth** [comment]
已經計入稅單稅是不會回溯的

**Comment by yakumoakatsuki** [comment]
上次登入時間：2017/09/27 09:55:39
上次登入IP：117.136.79.150
本季度未登入天數：0 
昨天我晚上7点多还在线上，早上7点半登录了一次，然后9点多上线的时候我就多了2000僵尸税。
想这是系统出了bug我也没打算理，卖股票交税的时候提示我有税没交，不能卖股票，股票不能卖我又没钱交税，希望能改善一下这些问题。
