### ISSUE TITLE
我是大陸券商產品負責人，希望與貴平臺接洽

### ISSUE THREAD

**Issue by yiricom** [mrbigmouth/acgn-stock#104]
我是大陸頂級券商的產品部負責人，可以給我你們團隊的聯繫方式嗎？我們對這個創意非常有興趣，期望能夠接洽并合作。可以與我電郵 61661168@qq.com 做初步溝通，或者請回貼告知貴方的聯繫方式，謝謝。

**Comment by mrbigmouth** [comment]
呃，如果是想開分站的話，程式碼直接拿走就可以了，License是MIT。

關於現在正在進行的網站(http://acgn-stock.com)，因為有捐款問題（包括現在的伺服器也是別人捐的），我並不把自己視為網站的唯一所有者。
因此想要合作的話可能公開來講會比較好，到時合作與否會以提案的方式移到遊戲討論區進行投票。

**Comment by yiricom** [comment]
好的，明白。我們尊重互聯網的分享及貴站的宅精神，我們也理解由于公眾捐款的存在，您不把網站視為唯一所有者的事實。另外，GITHUB上溝通確實不太便利，可否得到您的私人聯繫方式，如電郵或者其它更便捷的聯絡方式。后續我們希望以您為網站代表來做進一步溝通。您可否發一封say hello郵件至 61661168@qq.com ，這樣我們能夠建立更為便捷之交流。

**Comment by mrbigmouth** [comment]
ok

**Comment by yiricom** [comment]
如果需要我的工作郵箱及職位證明，亦可提供。我是大陸知名上市券商的產品負責人。

**Comment by Udre** [comment]
手機認證只能防止個人的分身，並不能防止公關或是網軍的分身。如果與大陸合作建議考慮阿里和騰訊，因為只有這兩個企業能根據用戶綁定的銀行卡確定身份唯一性⊙ω⊙

**Comment by mrbigmouth** [comment]
原則上要合作都會公開來啦，不用擔心。
（然後這個人自從要走我的Email確認是我之後就沒下文了）

**Comment by yiricom** [comment]
不是，我是要到您的聯絡電郵后去和公司彙報，不是沒有下文啦。大機構的流程和會議比較多，請見諒

**Comment by yiricom** [comment]
阿里和騰訊肯定是最好的，但是他們如果需要，可以隨時自己弄一個出來，應該不會注意到您這個啦。
