### ISSUE TITLE
教學區有嚴重影響文意之描述錯誤

### ISSUE THREAD

**Issue by ILIKEACG** [mrbigmouth/acgn-stock#105]
在第8大點 : 股票的交易

......若該公司存在三筆以單價10、15、20『『『購入』』』10股股票的訂單，此時有人下達了以單價15『『『購入』』』25股股票的訂單，則此訂單會先以20單價賣出10股......

大家都是「購入」，怎麼還會有賣出，誰賣的...? 第二個「購入」應該是要改成「賣出」，文意跟邏輯上才會正確吧?

**Comment by mrbigmouth** [comment]
dc82a22f81908abe544240fce0e6da3e08b96169
感謝提醒，今晚更新後修正。
