### ISSUE TITLE
董事會留言

### ISSUE THREAD

**Issue by KyotoAnime** [mrbigmouth/acgn-stock#11]
董事會留言有時會出現錯誤訊息
Match failed [400]
時好時壞@@

嘗試後發現似乎是在其他分頁會有問題
也就是我先開一個分頁操作正常
再開另一個分頁留言就會錯誤

**Comment by mrbigmouth** [comment]
你是用google帳號登入的嗎？

**Comment by KyotoAnime** [comment]
ptt 帳號就是KyotoAnime
現在仍有一樣的問題
瀏覽器是firefox

**Comment by mrbigmouth** [comment]
不知道為啥
多視窗的情況下有機會發生後端不認得前端是誰
導致驗證錯誤的情況
這牽涉到Meteor比較核心的系統了
暫時無法處理

**Comment by mrbigmouth** [comment]
經實驗
每次開新視窗時如果再重新整理一次就太會發生這個問題

**Comment by KyotoAnime** [comment]
ok 沒關係 反正這也不4太大bug 只是發現了就提一下

感謝!

**Comment by mrbigmouth** [comment]
剛重新檢視過log，似乎是我搞錯了，等今晚的修正後試看看吧。
