### ISSUE TITLE
產品中心的季度跟實際的相差一周

### ISSUE THREAD

**Issue by empti3** [mrbigmouth/acgn-stock#110]
https://i.imgur.com/JMGSrab.png
這裡的日期應該是9/24~9/30 (現在進行中的賽季)

**Comment by mrbigmouth** [comment]
其實這不是bug，上面顯示的是「這些產品被上架的日期」。
可以被投推薦票的產品都是「屬於上個季度的產品」沒錯。

至於顯示上該怎麼調整比較好我再想想。

**Comment by mrbigmouth** [comment]
今晚修正。
