### ISSUE TITLE
暗色主题下经理人的红色显示bug

### ISSUE THREAD

**Issue by sharp-tasting** [mrbigmouth/acgn-stock#115]
如图，当股价上涨的时候股票价格数字几乎无法看清，希望调一下配色
<img width="260" alt="screen shot 2017-10-01 at 17 08 42" src="https://user-images.githubusercontent.com/13917842/31053225-67a15518-a65e-11e7-99e6-521fbc139aad.png">

**Comment by mrbigmouth** [comment]
@silentvow
