### ISSUE TITLE
關於巴哈手機驗證

### ISSUE THREAD

**Issue by itemx** [mrbigmouth/acgn-stock#116]
我的帳號因為是早期帳號, 手機驗證的狀態會是 "永久" 導致無法正常於本站驗證
請考慮將此狀態也視為 "有通過手機驗證"

Ref: [個人首頁](https://home.gamer.com.tw/homeindex.php?owner=itemx)

**Comment by mrbigmouth** [comment]
已修正

**Comment by mrbigmouth** [comment]
好像還有點問題，明天再修

**Comment by redwildwing** [comment]
我這邊也有一樣的問題，再麻煩了

**Comment by mrbigmouth** [comment]
待會的修正應該能好。
