### ISSUE TITLE
『產品中心』可以看到被查封的公司產品

### ISSUE THREAD

**Issue by ouovouo** [mrbigmouth/acgn-stock#117]
『產品中心』可以看到被查封的公司產品
看起來被查封的公司產品也有計算到 下季總產品裡
該公司經理在被查封前上產品 囧
https://acgn-stock.com/company/detail/a7fSyhvnHsrZJ6Cff

<img src="https://i.imgur.com/1JdoxRh.png">

**Comment by mrbigmouth** [comment]
有效能問題，而且感覺影響不嚴重，應該不會進行處理。
