### ISSUE TITLE
投資新創的金錢累加

### ISSUE THREAD

**Issue by BassyKuo** [mrbigmouth/acgn-stock#119]
不知道是不是bug
原先已投資某新創
截止之前又再加碼
結果成立後只會計算到第一次的金錢，紀錄上也只有第一次投資訊息
但使用者帳戶是有被扣第二次的款

ex:
1. [10/1 15:02] 
投資A $550 (共投資$550)
帳戶剩餘 $2007

2. [10/1 20:03]
投資A $1957 (共投資$2507) `-> 當下新創網頁上有顯示正確投資金額，忘記check記錄中有無這筆`
帳戶剩餘 $50

3. [10/1 22:30]
A公司成立 (系統記錄：以$550得到x數量股票)
帳戶剩餘 $50

因為帳號記錄中找不到2的記錄，投資當下也沒截圖所以沒有佐證資料
不知道有沒有人碰到相同問題？
（可以考慮在帳號紀錄中新增帳戶金額的支出明細，不然好難比對XD）

**Comment by mrbigmouth** [comment]
有人有碰到相同問題嗎？

（是說你真的確定你有被扣到錢？|||）

**Comment by BassyKuo** [comment]
當下是真的有看到錢投資下去
但我剛剛把進帳支出一筆一筆抓出來計算，跟目前的餘額對得上
不知道跟昨天recovery有沒有關係

主要是怕這是bug
不過現在餘額跟帳對得起來，看來應該沒事了
