### ISSUE TITLE
高木同學計劃日期異常

### ISSUE THREAD

**Issue by JeremyShih** [mrbigmouth/acgn-stock#12]
現在是8/24 16:00，高木同學計劃日期：2017/08/25 04:15:00

**Comment by KyotoAnime** [comment]
大大，計畫日期是GM主動設定的，這並非異常喔!

**Comment by JeremyShih** [comment]
請問GM是指發起人還是經理人嗎?

**Comment by KyotoAnime** [comment]
Game Manager 就是開發遊戲的 mrbigmouth 大大
目前大部分計劃都是之前公測成功上市的，因為重置而回到新創
這些是由GM編排的時間順序，除了他以外玩家無法決定

如果現在自己創立一個全新的計畫，那就會是由創立時間點開始一個小時為期限

**Comment by mrbigmouth** [comment]
這次重置資料前就有說喔，故意把新創計劃的時間錯開避免同時間結算讓系統爆炸。

**Comment by JeremyShih** [comment]
了解...不好意思我沒有看完更新說明
