### ISSUE TITLE
使用者介面及使用者經驗優化

### ISSUE THREAD

**Issue by yeh19921026** [mrbigmouth/acgn-stock#120]
目前打算做一些不用架伺服器也能幫上忙的
這兩天都在外面用手機板看股票
發現使用者介面有蠻大的問題

然後使用者經驗也需要被優化
不然大家都要花一段時間去熟悉

我會改一些介面的問題，
但是要麻煩幫我測試一下成果才行...

**Comment by mrbigmouth** [comment]
所以你是要怎麼樣的幫忙？

**Comment by yeh19921026** [comment]
目前會先看有沒有地方讓我架測試的伺服器，
如果有的話我就能自己測試UI，

如果沒有的話就要再另外想辦法，
看有沒有人能幫我測試改完的html還能不能動。

目前我這邊主要改寫的地方應該都只是html檔，
手機板的UI我想優化的地方蠻多的，
至少像是繳稅那邊根本看不到東西的情況都會改善。

然後UX的部分就只能用提供建議的方式了，
碰到js的地方因為我因為環境沒辦法弄好連Meteor的教學都沒辦法跑完，
所以架構那些的我都還不是很了解。

**Comment by mrbigmouth** [comment]
目前可能沒辦法提供server，
而且如果你不是直接改原始碼，到時候也得再找人套進程式，
可能還是要請你再研究一下Meteor。
