### ISSUE TITLE
帳號資訊頁顯示調整

### ISSUE THREAD

**Issue by erase2004** [mrbigmouth/acgn-stock#121]
> (2017/10/02 09:13:04) 【舉報違規】 moonlordhk 以「苦力怕娘（爬行娘）已被沒收，但帳號資訊仍可看見為苦力怕娘（爬行娘）的總經理」的理由向金融管理會舉報 moonlordhk (218.252.45.49)的違規行為。

這應該只是算顯示上的問題，查封公司設計上也不會拔掉總經理，畢竟有恢復的可能
所以在帳號資訊頁，如有已查封公司的總經理資訊，顯示上可能調整為
1. 不顯示該筆資訊
2. 顯示該筆資訊，但與一般顯示當所使用的文字樣式不同，或加上查封的icon，以做區別

**Comment by mrbigmouth** [comment]
待會的更新會修正。
