### ISSUE TITLE
新创计划的翻页+返回问题

### ISSUE THREAD

**Issue by sharp-tasting** [mrbigmouth/acgn-stock#122]
比如翻到第二页 https://acgn-stock.com/foundation/2 ，然后随便点进一个公司，再用浏览器返回（后退），此时域名虽然变回 https://acgn-stock.com/foundation/2 ，但实际上显示的却是第1页，并且点下图的2并不能跳转第二页，只好点个其他页面才能点2
![image](https://user-images.githubusercontent.com/13917842/31062763-c14256f0-a6f2-11e7-8b79-8baba9e840c9.png)

**Comment by mrbigmouth** [comment]
待會的更新會修正。
