### ISSUE TITLE
抽稅沒更新

### ISSUE THREAD

**Issue by isaswa** [mrbigmouth/acgn-stock#123]
如圖 我的殭屍稅沿用了上個商業季度的資料而未更新
我這季的未登入次數是0
https://i.imgur.com/USbNNC4.png

**Comment by mrbigmouth** [comment]
帳號ID給一下（帳號資訊頁面網址列上的識別碼）

**Comment by isaswa** [comment]
isaswa

**Comment by isaswa** [comment]
2Kr4v22Hz7ofhRegD
