### ISSUE TITLE
殭屍稅判定

### ISSUE THREAD

**Issue by alex94539** [mrbigmouth/acgn-stock#125]
之前有看到回報
8:00上線
隔天8:03分上線，就因超過24小時被系統判定殭屍
是不是改成47小時59分判定一次會比較好?

**Comment by mrbigmouth** [comment]
根據https://www.ptt.cc/bbs/C_Chat/M.1505571902.A.0C6.html的推投結果，
一日不上線之帳號就是不發薪的，
只是由於系統效能考量，才改為用殭屍稅的方式將薪水扣回來。

要改成兩邊判定一次的話請去提案推頭翻案。
