### ISSUE TITLE
低價釋股爆量

### ISSUE THREAD

**Issue by PXMart** [mrbigmouth/acgn-stock#126]
解魯 公司
(2017/10/02 23:53:13) 【公司釋股】「 解魯 」公司以$4的價格釋出了2447數量的股票到市場上套取利潤！
他原本的股只有2103啊
好像爆得有點多，是BUG嗎

**Comment by zozotintin** [comment]
這屬於正常現象，有關詳細內容請參閱教學導覽裡的低量釋股規則。ACGN Stock感謝您的合作！
