### ISSUE TITLE
公司頁面的UI有點彆扭

### ISSUE THREAD

**Issue by isaswa** [mrbigmouth/acgn-stock#127]
不知道能不能新增一個功能：個人的偏好設定
讓點開一個公司的時候 可以自己選預設展開哪些區塊
（股價趨勢／數據資訊...等）

**Comment by mrbigmouth** [comment]
現在只要不重新整理或開新頁面，就會自動幫你記住你展開哪些區塊了。
真要做新的偏好設定功能也會放到最後優先度才做。
