### ISSUE TITLE
新創計畫是否能新增排序功能

### ISSUE THREAD

**Issue by isaswa** [mrbigmouth/acgn-stock#129]
例如根據 投資人數 總投資額 截止時間等 ...

**Comment by mrbigmouth** [comment]
投資相關排序因為資料結構跟系統效能的關係不行。
目前已經是照截止時間排序了。

**Comment by isaswa** [comment]
這點（目前的排序規則）要不要寫在新創計畫頁面明顯一點的位置
我自己也是觀察了一下才發現是照截止時間排的
會讓人一開始有點混亂

**Comment by isaswa** [comment]
畢竟每次都看計畫要每一頁都掃過一次有點累人
