### ISSUE TITLE
帳號認證方式重新推投結果

### ISSUE THREAD

**Issue by mimo123483** [mrbigmouth/acgn-stock#133]
https://www.ptt.cc/bbs/C_Chat/M.1506740614.A.AAE.html

你好，經過重新推投，目前的結果是「禁止新建Gmail帳號但不溯既往」並在「本遊戲賽季」執行。
如果方便的話，再請協助處理這項議案，感謝！
(可能可以用停止對Gmail帳號發出認證信的方式處理？)

禁止新建Gmail帳號但不溯既往 32票 vs 維持原樣 2票
本遊戲賽季執行 27票 vs 下個遊戲賽季 5票

**Comment by mrbigmouth** [comment]
中午修改，記得在原文以編修或回文的方式註記結果，方便日後查閱。
