### ISSUE TITLE
廣告相關問題

### ISSUE THREAD

**Issue by erase2004** [mrbigmouth/acgn-stock#136]
1. 金管會撤銷廣告沒有理由資訊可以填寫

2. 撤銷廣告操作的訊息格式有問題

(2017/10/06 22:32:48) 【撤銷廣告】 erase2004 將 erase2004 發布的廣告「「測試撤銷message」給撤銷了。

  多了 「 和 結尾的 message

3. 創建廣告者無法提早撤銷廣告

**Comment by ouovouo** [comment]
我記得創建廣告者無法提早撤銷廣告是因為別人可以投錢，所以不開放撤銷廣告

**Comment by mrbigmouth** [comment]
已修正紀錄訊息錯誤的問題。
