### ISSUE TITLE
已被判分身的帳號持股變殭屍股

### ISSUE THREAD

**Issue by Soragod** [mrbigmouth/acgn-stock#139]
https://acgn-stock.com/accountInfo/yGaTj3HnYpkbqn6G6
類似這種帳號變成殭屍股好像沒有回收機制 像李恩的股他跟分身就持有250股全都變殭屍股 好像沒看到有解決機制

**Comment by mrbigmouth** [comment]
金管會可以沒收股份，請金管會處理。
