### ISSUE TITLE
角色日文名字及中港台三地譯名的搜索問題

### ISSUE THREAD

**Issue by yangzhaofeng** [mrbigmouth/acgn-stock#140]
目前並沒有辦法強制創建者加搜索標籤
有的角色如花園たえ（花園多惠）等在使用日文搜索的時候就搜不到，還有用穗乃果的日文寫法穂乃果也搜索不到對應的角色
再有如使用矢澤にこ的香港譯名矢澤妮歌搜索的時候也無法找到
我有個建議，就是提示使用多語言角色名，如日文原名，台灣譯名，香港譯名，大陸譯名，民間常用譯名之類的。（英文譯名不知有沒有必要）

**Comment by yangzhaofeng** [comment]
可以在創建新角色的時候搜索tag框下面加一句
「建議在搜索標籤中加入日文原名、中國大陸及香港等各地譯名以便搜索」
或者新的角色可以加入一些名字屬性，例如
角色名（日文原名）：矢澤にこ
中文譯名（台灣）：矢澤日香
中文譯名（香港）：矢澤妮歌
中文譯名（中國大陸）：矢泽日香
英文譯名/羅馬音：YAZAWA NICO
常用譯名1：矢澤妮可
常用譯名2：矢澤仁子
之類的
之後全部作為搜索tag或者其他可以用於搜索的屬性處理
這樣也可以將公司的命名規範化，在一定程度上避免重複創建角色

**Comment by Soragod** [comment]
個人覺得強制依日版維基百科上名稱為唯一可創建名稱 已創建的可能需要麻煩後台檢查改過來

**Comment by Soragod** [comment]
不過有問題 有些角色維基百科上沒有  或 日文版沒有 只有韓文 英文有....

**Comment by mrbigmouth** [comment]
已加入提示。
