### ISSUE TITLE
稅務問題 關於殭屍稅

### ISSUE THREAD

**Issue by piggg4** [mrbigmouth/acgn-stock#145]
系統還會在季度結束時計算每名使用者在該季度的未登入天數，並課以每天$1000的殭屍稅。
可是我該季度天天都有上，依樣被課了3000的殭屍稅?
https://i.imgur.com/8BsFY4Q.jpg

**Comment by mrbigmouth** [comment]
與  #138 問題相同。
目前狀態是測不到bug中。（我自己測未登入天數跟殭屍稅計算時都沒問題.....）

**Comment by terry12369** [comment]
雖然測不到BUG，但莫名被扣了3000塊讓人很不爽啊，有沒有什麼補救的方案，還是這3000就只能算我衰......
