### ISSUE TITLE
洽談合作

### ISSUE THREAD

**Issue by beenick219** [mrbigmouth/acgn-stock#147]
不好意思，如果有想跟貴單位合作的話
不知可否恰談
謝謝

**Comment by mrbigmouth** [comment]
1.想要商業化或者修改啥的，本專案License是MIT，Code自取，只要保留原作者姓名就可以任意改動。
2.其他合作事宜，目前本專案應該算是所有使用者共有的，建議直接在這邊談想合作的方式，我會另外進行轉達並由全體使用者投票表決。（當然如果你有辦法直接到PTT張貼討論文那更好 XD。）
