### ISSUE TITLE
8/25 推薦票額度

### ISSUE THREAD

**Issue by papago89** [mrbigmouth/acgn-stock#15]
今日季度更換後每人有11張推薦票 單票價值12727營利額 總額約為14萬 是否為設定錯誤?

(2017/08/25 09:31:26) 【推薦產品】 papago89 向「 雪之下雪乃 」公司的產品「 gungunit - [果青] 同人-他和她的冬日仍在持續 」投了一張推薦票，使其獲得了$12727的營利額！

**Comment by mrbigmouth** [comment]
沒有錯誤喔！
之前公測時一個商業季度為一天，每個人推薦票的可產生營利是是兩萬，
現在一個商業季度為七天，每人推薦票的可產生營利就是七倍十四萬。

**Comment by mrbigmouth** [comment]
啊等等，之前的推薦票只有兩千嗎！？
我一直以為是兩萬！？

這樣的話，先看看公測前的營利總額是不是太多，
到時再視情況決定推薦票的額度該有多少吧。

**Comment by mrbigmouth** [comment]
已照提案投票結果修改。
