### ISSUE TITLE
巴哈姆特帳號無法登錄

### ISSUE THREAD

**Issue by chunhimlai** [mrbigmouth/acgn-stock#151]
![c](https://user-images.githubusercontent.com/32769154/31544868-71686640-b04f-11e7-9339-ceb2a1d87a17.png)
https://home.gamer.com.tw/homeReplyList.php?owner=chunhimlai1

我的帳號早已經完成驗證, 但前幾天突然要求驗證並且每次系統稱無法查詢到驗證碼

**Comment by mrbigmouth** [comment]
大小寫有差，請確定你註冊的帳號也是Chunhimlai1，而不是chunhimlai1。
