### ISSUE TITLE
測試中的規則討論頁面在投票後無法關閉對話框

### ISSUE THREAD

**Issue by yangzhaofeng** [mrbigmouth/acgn-stock#152]
如圖所示
http://home.ustc.edu.cn/~yzf2015/pic_proxy/Screenshot_20171013-195257.png

**Comment by yangzhaofeng** [comment]
所用瀏覽器為 Chrome Dev 63.0.3236.6
手機為 Google Pixel
系統為 Android 8.0.0

**Comment by mrbigmouth** [comment]
@silentvow
