### ISSUE TITLE
經營編輯頁面產品大小圖的問題

### ISSUE THREAD

**Issue by redwildwing** [mrbigmouth/acgn-stock#153]
您好
因為我有自用空間，所以之前大小圖都習慣放在自己的空間上
但最近編輯大小圖時，在想變換圖片網址時會出現
**「http://www.xxx.com/xxxx.jpg」並非合法的網址！ [403]**
的訊息，請問現在是否有限定要使用imgur的網址才行呢?

謝謝

**Comment by mrbigmouth** [comment]
沒有這種限制，但是系統會先去該網址抓圖片，確定該網址抓下來的檔案是圖片的格式。
（主要以https://github.com/sindresorhus/image-type這個套件驗證）
如果無法通過驗證，檢查一下圖片格式跟網址的reponse type吧？
