### ISSUE TITLE
角色的圖片上傳功能對於https傳輸圖片的處理問題

### ISSUE THREAD

**Issue by yangzhaofeng** [mrbigmouth/acgn-stock#159]
如這張圖
https://images-na.ssl-images-amazon.com/images/I/71vRSt4fZbL.jpg
如果將s去掉則server會返回403，但是在將其加入角色圖片的時候似乎會強制用http來檢查，最終被認定為非合法的網址

**Comment by mrbigmouth** [comment]
已修正
