### ISSUE TITLE
關於公司圖片上傳問題

### ISSUE THREAD

**Issue by CHIA23** [mrbigmouth/acgn-stock#16]
您好
我剛剛想將公司的大.小圖片換掉.但有兩個問題
1.我圖換了之後還是原本的圖(剛剛換圖才出現的問題)
2.圖片按照規格上傳但常常會顯示圖片過大無法上傳(這問題之前就有)

**Comment by mrbigmouth** [comment]
1.這是因為瀏覽器快取的問題，嘗試重新整理清快取或者開無痕式視窗就可以看到新圖了才對。
2.因為系統的流量是要錢的，對圖檔大小進行限制是必要的。你可以嘗試將圖片壓縮後再上傳，有很多圖片壓縮工具可以利用。如：[http://compressimage.toolur.com/](http://compressimage.toolur.com/)
