### ISSUE TITLE
公司釋出股票

### ISSUE THREAD

**Issue by six60107** [mrbigmouth/acgn-stock#161]
現在很容易就發生經理人釋出股票 然後自己1個人全買走
我覺得應該限制經理人1天能夠購買釋出股幾%
或者是在顯眼的地方提前公告要釋出新股,個人建議釋出股票前3天公告

**Comment by mrbigmouth** [comment]
經理人並沒有在購買釋出股票上有任何優勢，跟所有其他使用者一樣，理論上沒有任何理由對經理人特別限制。
而且這類修改需要按照章程進行討論推投。
