### ISSUE TITLE
[voted]渡假模式

### ISSUE THREAD

**Issue by YUN-Lee** [mrbigmouth/acgn-stock#178]
投票網址：https://acgn-stock.com/ruleDiscuss/view/ZqCZSvfFbckeyrPrc
讓玩家暫時無法操作時，以凍結部分自身之權力，保持帳號的狀態，不必擔心這期間的稅金增長過多以致於無法應付。

啟動條件：
1.無擔任經理人且無競選經理人。如有擔任，系統會顯示[經理及競選中之經理無法使用此模式]，且無法放假
2.無任何交易訂單。如有訂單，系統會顯示[請清空所有買賣單，才能進行放假]，且無法放假
3.已繳交完所有的稅。如有稅金，系統會顯示[請繳交完稅金，才能進行放假]，且無法放假
4.無擔任董座。如有擔任，系統會顯示[公司懂座無法使用此模式]，且無法放假
5.不得為儲備員工。如有擔任，系統會顯示[儲備員工無法使用此模式]，且無法放假

渡假模式之定義及其權力限制：
1. 帳號資訊頁面、董事會列表會顯示【渡假中】
2. 玩家會收到開始渡假前當週活動時的分紅與稅金，稅金可延後繳交
3. 渡假最長可至賽季結束前二週
4. 渡假中不會產生新的分紅及稅金
5. 一旦進入渡假模式，會立刻凍結[下單]、[廣告]、[投資新創]、[員工報名]、[參選及支持經理人]之能力
6. 僵屍稅為500資金
7. 渡假時不能投推薦票

解除渡假模式：
1. 點選「收假」按鈕，統一週日分紅計算後再收假。
2. 申請度假當季的稅金，繳交期限遞延至收假日翌日起算第三日上午八點。
3. 欲再申請渡假，需間隔上次收假一週以上。

**Comment by frozenmouse** [comment]
這個我認領 ._./
