### ISSUE TITLE
關於方糖社亂象

### ISSUE THREAD

**Issue by Soragod** [mrbigmouth/acgn-stock#180]
舉例
https://acgn-stock.com/company/detail/962cvGaC7TYhyxCaw
來說
在介紹上 警告其他投資人不准下單 必須跟他聯繫的警告行為 
雖然金管會目前不管  
這個是否有違反本遊戲系統為公開市場的基本原則?

**Comment by mrbigmouth** [comment]
這類問題請用遊戲內功能聯絡金管會，或者前往PTT的ACGN_Stock板討論。
