### ISSUE TITLE
我的最愛太長的時候，最下面一間會被擋住

### ISSUE THREAD

**Issue by softbearlolz** [mrbigmouth/acgn-stock#198]
如標題，我的最愛太長的話 最下面的那個 會被Bug回報 伺服器連線數量：190這行擋住

**Comment by mrbigmouth** [comment]
@silentvow

**Comment by silentvow** [comment]
#199

**Comment by softbearlolz** [comment]
![2017-11-14 23 07 10](https://user-images.githubusercontent.com/18229437/32787072-9b614cfa-c990-11e7-8aa5-a195580f8423.png)
沒字了

**Comment by silentvow** [comment]
#206
