### ISSUE TITLE
歷史產品記錄過長

### ISSUE THREAD

**Issue by isaswa** [mrbigmouth/acgn-stock#203]
一個家公司推出過的產品如果很多的話
在公司頁面會全部顯示 這樣可能會有越來越多的問題
有沒有考慮只顯示前幾名(我記得以前某個版本只有顯示前三?)

**Comment by mrbigmouth** [comment]
這裡其實有做分頁，只是不知道哪時候改成一頁三十筆了.....

**Comment by frozenmouse** [comment]
@isaswa 你是指公司頁面產品中心右邊那欄的暢銷產品？

@mrbigmouth 有做分頁然後被改成一頁 30 筆的是「更多…」按進去之後的公司產品中心，後端訂閱丟出來是一頁 30 筆但前端當初寫 10 筆

**Comment by mrbigmouth** [comment]
所以說當初那個其實不是Bug，
右邊的歷史頁面事實上完全沒有做分頁啊啊啊！XD
那邊是故意只顯示十筆的，避免顯示過長。
（至於後端吐了三十筆過來？管他的！）

**Comment by frozenmouse** [comment]
@mrbigmouth 不好意思，我記反了XD
是 https://github.com/mrbigmouth/acgn-stock/commit/8fb88842e7408d9cfae91509aba5730289ac4787 改的
應該是前端顯示 30 筆一頁，後端丟 10 筆一頁
也就是說換頁時第 11~30 筆會不見 ˊ_>ˋ
