### ISSUE TITLE
新創ID顯示bug

### ISSUE THREAD

**Issue by we684123** [mrbigmouth/acgn-stock#209]
如圖最下方
https://imgur.com/eggaS5W
https://imgur.com/vmsDZGb
在閒置頁面時，如有新低價投資者投資
最下面的ID會重複
重新整理後才好

新創網址https://acgn-stock.com/foundation/view/nip2vC2qgDS3L6zv2

**Comment by mrbigmouth** [comment]
沒測出bug說。

**Comment by frozenmouse** [comment]
#491 已經解決了這個問題
