### ISSUE TITLE
還在輸入角色介紹的時候被回朔了

### ISSUE THREAD

**Issue by cyanuser1** [mrbigmouth/acgn-stock#211]
如題

**Comment by frozenmouse** [comment]
需要詳細的狀況，什麼回朔？

**Comment by mrbigmouth** [comment]
我猜是編輯公司資料時，因為其他資訊的變動（釋股、最後交易價格更新）導致正在編輯的資料被新資料給蓋掉？
暫時將編輯時所訂閱的資料限制為能編輯的欄位試試看。
4726b09b58cd94325a43f23bc5bf12b2415ab359
是說這個修正當時被混到其他commit裡面了。

**Comment by cyanuser1** [comment]
並不是被新資料蓋掉，而是變回編輯前、原來的內容
