### ISSUE TITLE
久久沒玩上線金錢變成負的@@

### ISSUE THREAD

**Issue by gyc880323** [mrbigmouth/acgn-stock#222]
如題
請問是為什麼@@
這樣我根本也無法開始阿

**Comment by frozenmouse** [comment]
這是正常現象
因為系統每個商業季度產生的稅若是遲交過久，會將你的股票和現金資產拿來扺掉
若有需要可以聯絡金管會為你重置帳號，讓你的錢回到初始的 10000 元

**Comment by gyc880323** [comment]
那如果重製的話 之前的聖晶石會不見嗎

**Comment by frozenmouse** [comment]
不會不見，金管會沒辦法動到聖晶石的
