### ISSUE TITLE
無法安裝

### ISSUE THREAD

**Issue by shuhanliu** [mrbigmouth/acgn-stock#227]
輸入meteor npm install後顯示

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> bcrypt@1.0.3 install /root/acgn/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v57-linux-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@8.8.1 (node-v57 ABI) (falling back to source compile with node-gyp)
make: Entering directory `/root/acgn/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory `/root/acgn/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.meteor/packages/meteor-tool/.1.6.0.35z9z0.b3u3n++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-042stab123.9
gyp ERR! command "/root/.meteor/packages/meteor-tool/.1.6.0.35z9z0.b3u3n++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node" "/root/.meteor/packages/meteor-tool/.1.6.0.35z9z0.b3u3n++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/acgn/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/root/acgn/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /root/acgn/node_modules/bcrypt
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/root/.meteor/packages/meteor-tool/.1.6.0.35z9z0.b3u3n++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node /root/.meteor/packages/meteor-tool/.1.6.0.35z9z0.b3u3n++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/acgn/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/root/acgn/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/acgn/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 2.6.32-042stab123.9
node-pre-gyp ERR! command "/root/.meteor/packages/meteor-tool/.1.6.0.35z9z0.b3u3n++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node" "/root/acgn/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/acgn/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/root/.meteor/packages/meteor-tool/.1.6.0.35z9z0.b3u3n++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node /root/.meteor/packages/meteor-tool/.1.6.0.35z9z0.b3u3n++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/acgn/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/root/acgn/node_modules/bcrypt/lib/binding' (1)
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-26T14_51_19_192Z-debug.log

**Comment by mrbigmouth** [comment]
OS? nodejs版本？

**Comment by shuhanliu** [comment]
Centos 6.4

**Comment by shuhanliu** [comment]
請問壹下，妳推薦的OS是什麽？

**Comment by shuhanliu** [comment]
妳好，我安裝了新的centos 和 nodejs,已經安裝成功
但是運行meteor run --settings config.json這壹步時會提示

You are attempting to run Meteor as the 'root' superuser. If you are developing, this is almost
certainly *not* what you want to do and will likely result in incorrect file permissions. However,
if you are running this command in a build process (CI, etc.), or you are absolutely sure you know
what you are doing, set the METEOR_ALLOW_SUPERUSER environment variable or pass --allow-superuser
to proceed.

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app directory will be
incorrect if you ever attempt to perform any Meteor tasks as a normal user. If you need to fix your
permissions, run the following command from the root of your project:

  sudo chown -Rh <username> .meteor/local

請問這個怎麽解決，謝謝

**Comment by mrbigmouth** [comment]
他不是講的很清楚了？  run的時候加--allow-superuser參數，然後以sudo chown -Rh .meteor/local修改權限

但是我建議還是不要用root權限去跑meteor，因為整個Meteor程式就不是設計來給root權限跑的。
如果你只是想把port設在80，可以用iptables指令去轉。
sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000
