### ISSUE TITLE
圖片更新問題

### ISSUE THREAD

**Issue by alex94539** [mrbigmouth/acgn-stock#23]
如題

在經理人更換圖片之後，經理人本人看到的圖片並沒有更新

但以其他帳號觀看是有更新的

經理人本身帳號無論更換幾次看到的圖片都是最一開始新創時放入的

經理人帳號觀看(PM8:14)
![image](https://user-images.githubusercontent.com/31380333/29749692-6599a7e4-8b64-11e7-97ee-e7fe85c42036.png)
同一時間以其他帳號觀看
![image](https://user-images.githubusercontent.com/31380333/29749699-875afd60-8b64-11e7-9530-f1333fa84b35.png)

**Comment by mrbigmouth** [comment]
就圖片被瀏覽器快取住了，清掉瀏覽器的快取或開其他瀏覽器/無痕模式都可以看到新圖片。
