### ISSUE TITLE
[voted]資本額 (capital amount)

### ISSUE THREAD

**Issue by speedypard** [mrbigmouth/acgn-stock#240]
投票網址：https://acgn-stock.com/ruleDiscuss/view/CfXgtrAbqe2Y4vkzG
資本額、資本額修正之員工獲利模型、挖礦機（包含資本額修正模型）將會切割成多個Issues

● 資本額為＝初始募得總資金+釋股＊釋股股價
● 釋股所獲得的資金將不會計入獲利並分紅
● 增加資本額欄位公司資訊
● 增加上個商業季度之資本額排名

**Comment by frozenmouse** [comment]
這個我這兩天來弄 ._./
