### ISSUE TITLE
[voted]員工模型函數修正（資本額）

### ISSUE THREAD

**Issue by speedypard** [mrbigmouth/acgn-stock#249]
公司等級：
依照上個商業季度之資本額排名，將公司依照其PR 25,50,75,100，分成4個等級： A, B, C, D。

（x為員工總數，t為公司等級參數，A, B, C, D等分別對應：0.4, 0.3, 0.2, 0.1）
員工營利模型修正為：
每日基礎營利額(b)＝3000 * (0.9+t)
每日公司總基礎營利額＝每日基礎營利額(b)＊總人數(x)＝3000 * (0.9+t) * x
員工爆肝：
在一定機率(R)下會發動的增幅作用，每位員工皆有可能發動，發動後之公司每日總營利會加上總爆肝量，即：每日公司總基礎營利額+每日總爆肝量。
每日總爆肝＝爆肝量(Rv)＊爆肝人數(Rx)
爆肝量(Rv)＝每日基礎營利額(b)＊公司等級參數(t)，即 Rv = b * t
爆肝人數(Rx)＝人數為 0～x 人
爆肝率(R)：爆肝之發動機率，為(x~30)%
每日總爆肝量＝爆肝量(Rv)＊爆肝人數(Rx)＝ 3000 * (0.9+t) * t * Rx
每日公司總營利＝基礎營利額+每日總爆肝量＝3000 * (0.9+t) * x + 3000 * (0.9+t) * t * Rx

**Comment by frozenmouse** [comment]
@mrbigmouth 這個還沒完成，只是先弄出第一點的分級而已
