### ISSUE TITLE
[voted] 獲利製造機 (generator)

### ISSUE THREAD

**Issue by speedypard** [mrbigmouth/acgn-stock#252]
投票網址：https://acgn-stock.com/ruleDiscuss/view/fYPZp3pKri65pW23y

公司等級：
依照上個商業季度之資本額排名，將公司依照其PR 25,50,75,100，分成4個等級： A, B, C, D。

公司：
（x為總礦石生產值，t為公司等級參數，A, B, C, D等分別對應：0, 0.1, 0.2, 0.3）
獲利函數模型為：6300 * ln(1+x) / ln(10) * x^t
●每個公司都會增加此獲利模型，依照「寄放」於公司的石頭總數、種類來生產獲利。
●公司增加「總生產值」欄位，計算總value。獲利結果於換季結算後再顯示，季中不用。
●玩家放入石頭時會產生log紀錄，同時「總生產值」欄位值增加。
●玩家需在下週結算前24Hr放入某個公司，並於下週結算後開始啟動運轉。
●如欲取回寄放的石頭，也需在下次結算前24Hr申請提領，一併於結算後自動釋放。
●如無任何提領的動作，石頭將會持續於該公司的挖礦機中，直到消滅或賽季結束。
●此外，每個人不論石頭類型，皆限制只能於一家公司放置一顆石頭。

玩家：
●增加「誕生石」欄位，生產值＝1。此石頭不會因為使用而消滅、不會累積至下個賽季。
每個人加入遊戲後會發放一顆「誕生石」，玩家可以將此結晶寄放在某甲公司下，
而甲公司就可以用此結晶依照生產公式來產生營利。
----------------------以下功能可慢慢再加入-------------------
●聖晶石，生產值為0.5。不會因為使用而消滅。
●彩虹石的碎片，生產值為2。「彩虹石的碎片」，可用10,000資金與系統兌換此，只能使用一次，結算後會自動消滅。
●彩虹石，生產值為5。可用100,000資金與系統兌換，只能使用一次，結算後會自動消滅，並變成「彩虹石的碎片」。
P.S. 「任務石」等到企劃部想完任務內容再實做。

**Comment by frozenmouse** [comment]
處理中 ☕️

**Comment by frozenmouse** [comment]
為簡化操作流程以及降低實作的複雜度，對於放置 / 取回石頭以及營利結算的部分，將進行修改：

* 商業季度結束前 24 小時定義為「礦機運作時間」，其餘則為「礦機閒置時間」
* 在「礦機閒置時間」裡，玩家可自由放置或取回石頭
* 在「礦機運作時間」裡，玩家無法放置或取回石頭
* 商業季度結算時，根據礦機的石頭數量，代入原 po 的獲利模型進行獲利結算，增加至當季的營利額，再進行分紅
* 完成上一步的礦機營利結算後，將消除那些會自動消滅的石頭（彩虹石→歸還等量的彩虹石碎片；彩紅石碎片→消失）

主要的差別在於：
* 玩家投入石頭後，挖礦機的營利是當季生成，而非原先的隔一季
  * 不再需要「總生產值」欄位輔助才能計算隔一季才產生的營利
* 玩家拿回石頭的操作是馬上生效的，而非原先的預約制
  * 不再需要處理拿回石頭的預約申請，只需在季末處理有特別設計的石頭（如彩虹石系列）即可
  * 玩家在礦機正式運作前可以隨時反悔，自由度較高
