### ISSUE TITLE
[希望新增功能] 於帳號資訊顯示董事長

### ISSUE THREAD

**Issue by softbearlolz** [mrbigmouth/acgn-stock#260]
希望能於帳號資訊頁面顯示目前為哪些公司的董事長

如
是「OOOO」公司的董事長。
是「OOOO」公司的總經理。
是「OOOO」公司的員工。

**Comment by erase2004** [comment]
一個問題，『是「OOOO」公司的董事長』這個的顯示，
董事長是寫死，就是固定顯示「董事長」，
還是那個董事長是公司裡面的「董事長頭銜」，
亦或「董事長(公司裡面的董事長頭銜)」這樣?

**Comment by softbearlolz** [comment]
我個人意見的話，我覺得保持一致性比較好(但是已經放在董事長分頁之下了，保持一致的必要性不高)。
如果其他玩家或是工程組覺得其他顯示方式比較好，我沒有異議。
