### ISSUE TITLE
希望能新增金管會在新創計畫加上違規tag之功能

### ISSUE THREAD

**Issue by TheDark0825** [mrbigmouth/acgn-stock#261]
雖抓取重複新創上標籤金管會職責外之事項
但依然希望金管會可以有個更明顯的標籤上法
在已經確定新創違規之時有個提醒玩家之手段
　
呈現樣貌類似於此圖：https://i.imgur.com/ikhF112.png
可由金管會自主增加TAG以利業務執行之方便
此功能正與erase2004與frozenmouse商議中
　
先發isuue以利查存

**Comment by frozenmouse** [comment]
這個我來做 ._./
