### ISSUE TITLE
[require] 進階帳戶管理

### ISSUE THREAD

**Issue by speedypard** [mrbigmouth/acgn-stock#287]
新增進階帳戶控制面板，以此來新增金管人員或企劃人員
[系統公告及廣告宣傳]
[帳戶資訊]
[公司資訊]
[規則討論]
以上5大項之進階功能建議分別獨立控制

**Comment by frozenmouse** [comment]
參照目前的組織方式，現在設立了以下身份組，以及其（已實作或預計加入的）權限：

* 超級管理員：指定營運總管（未實作）
* 營運總管：指定其他部門的成員（未實作）
* 工程部成員：觀看後台統計（未實作）、修改系統公告
* 企劃部成員：觀看後台統計（未實作）、規則投票的管理、修改系統公告
* 金管會成員：其他金管會的管理功能、修改系統公告

**Comment by frozenmouse** [comment]
在 #462 之後，這部分的功能已經算是完成了
