### ISSUE TITLE
目前的幾個問題

### ISSUE THREAD

**Issue by y2468101216** [mrbigmouth/acgn-stock#3]
1. 需要一個CI
2. 需要feature and bug

沒有這些難以提PR

**Comment by mrbigmouth** [comment]
要搞CI這技術需求太高端了我不會。
老實說貢獻者應該也不會很多（？）
只能請貢獻的人自己裝meteor在PR前跑一次。

然後其實我有做eslint設定，npm install後可以跑npm run lint來符合整體coding style。

**Comment by y2468101216** [comment]
https://travis-ci.org

免費的，不用跑test，讓他build過就好，連build都不會過得不能進。

**Comment by mrbigmouth** [comment]
https://circleci.com/gh/mrbigmouth/acgn-stock
