### ISSUE TITLE
即時訊息篩選BUG?

### ISSUE THREAD

**Issue by ouovouo** [mrbigmouth/acgn-stock#30]
即時訊息只有開 聊天發言 卻還可以看到自己的 【訂單完成】、【交易紀錄】、【購買下單】是刻意的嗎?

**Comment by mrbigmouth** [comment]
對
https://www.ptt.cc/bbs/C_Chat/M.1503765796.A.2CD.html
  4.所有跟自身有關的交易紀錄會自動在即時訊息中顯示，
    不會因為你篩掉了交易訊息就不顯示

**Comment by ouovouo** [comment]
自從即時訊息修復HTML的BUG後 一到晚上10點多還是11點多讀取就會越來越慢了
