### ISSUE TITLE
關於今日成交量及參考價格更新

### ISSUE THREAD

**Issue by supmiku39** [mrbigmouth/acgn-stock#33]
不好意思想請問一下關於今日成交量及參考價格更新的問題

說明頁上有寫說「每隔三到六小時的隨機時間，系統會以股票的當前交易價格取代其參考價格。」
今天有在關注叫做「芙蘭朵露·斯卡蕾特」的公司
它的股票於02:38成交2股在94元，之後又於10:07成交100股於100元

現在是18:02
網頁上的今日成交量顯示為100股(似乎沒有把02:38及以前的成交量算進去)
而參考價格仍維持在94元(照規則來說的話，最晚應該16:07就會更新到100元)
想請問一下本人的理解是否在哪些部分出了問題，謝謝

[18:45追記]
現在參考價格有調到100元了
看版上的聊天紀錄，好像是18:40更新的

**Comment by mrbigmouth** [comment]
系統重開機或更新程式時會重新計算紀錄時間。
