### ISSUE TITLE
請問殭屍戶持有的股票，是否能強制釋股?

### ISSUE THREAD

**Issue by Chancefaild** [mrbigmouth/acgn-stock#35]
因為發現很多持有股票的公司大戶，很多都3天以上沒上線。
是否要訂一個機制5天以上未上線強制以市價掛單賣出???? 這樣交易會比較活絡!

**Comment by Chancefaild** [comment]
還有是否要提供一種減資或下市的機制...........淘汰不良的公司

**Comment by mrbigmouth** [comment]
https://www.ptt.cc/bbs/C_Chat/M.1503647472.A.51F.html
想對股市規則進行修改，請試著照這篇的章程去PTT提案建議喔～
