### ISSUE TITLE
[voted] 經理選舉修改方案

### ISSUE THREAD

**Issue by speedypard** [mrbigmouth/acgn-stock#367]
https://acgn-stock.com/ruleDiscuss/view/Sr6Ptt7SeoyWwnNvC
提案人： carlow
內容：
- [ ] 1. 經理參選截止日期提早12小時至週五晚上。
- [ ] 2. 如果經理上季為活躍玩家(該季未上線天數<=3)，則上季支持該經理的活躍玩家(該季未上線天數<=3)預設自動支持該當選經理。
- [ ] 3. 如有多人競選，則現任經理自動參選，且支持率沿用[2]，不進行歸零。

**Comment by frozenmouse** [comment]
因未上線天數的運作問題，未登入的玩家不會更新此資料，將導致本提案的修改無法發揮應有的功能。
因此，這邊直接將條件改成「上次登入時間離選舉開始時間在三天以內」。
