### ISSUE TITLE
[voted] 公司打工自動續任儲備員工

### ISSUE THREAD

**Issue by speedypard** [mrbigmouth/acgn-stock#368]
https://acgn-stock.com/ruleDiscuss/view/b86GSJQnC58RrYGzd
提案人： vios10009
內容：未登入天數小於3日者，自動報名上季打工之公司。

**Comment by SoftwareSing** [comment]
本案公告之微調項目
https://acgn-stock.com/announcement/view/XWD8Y6P2MHvjCkHrt
1. 系統活躍玩家的判斷條件去除員工報名的判斷。
2. 在新季度開始時，所有活躍玩家會統一自動報名為目前擔任正職的公司的儲備員工。
（即自動報名下季正職員工）
