### ISSUE TITLE
 被死刑的用戶能把股票吐出來嗎？

### ISSUE THREAD

**Issue by huey2000exo** [mrbigmouth/acgn-stock#37]
http://acgn-stock.com/company/AfNFMaPuPCqzPECAD
這是繪里奈的股票，經理人和持有第二多股份的是同ip，被死刑了，問問有辦法把他的股票全數釋出嗎？還有把經理人換掉？

**Comment by mrbigmouth** [comment]
這邊金管會委員跟我提過數種作法，因為都很麻煩，所以我希望能通過表決決定一種之後我再去做。
https://www.ptt.cc/bbs/C_Chat/M.1503647472.A.51F.html
有更好的建議也歡迎按照這篇的章程在PTT提案討論。
