### ISSUE TITLE
[希望新增功能]投票系統防呆機制

### ISSUE THREAD

**Issue by WuLaMar** [mrbigmouth/acgn-stock#371]
為了防止投票時有人有些選項沒有選到而直接按下確定投票按鈕，希望在所有議題都有選取選項之狀態下才可完成投票。
如果是為了廢票而有這樣設計，則希望有個"你有沒投完的選項，是否要投票的框框跳出來"。

**Comment by mrbigmouth** [comment]
@silentvow
