### ISSUE TITLE
角色圖上傳

### ISSUE THREAD

**Issue by ouovouo** [mrbigmouth/acgn-stock#38]
角色圖可以用外部連結嗎?
現在有檔案大小限制 為了能成功上傳 我只能傳渣畫質版本QQ

**Comment by mrbigmouth** [comment]
理論上是可以換外部連結啦，過幾天來加看看。
是說，大部份的圖床如imgurl在「被特定網站」引用過多時好像是會鎖網域的。

**Comment by ouovouo** [comment]
imgurl 有提供api 給網站使用
http://api.imgur.com/

**Comment by mrbigmouth** [comment]
之後很可能會放廣告，不符合免費使用的條件。

**Comment by mrbigmouth** [comment]
已經改成直接讓經理放連結了。
