### ISSUE TITLE
關於GOOGLE帳號登入的建議

### ISSUE THREAD

**Issue by YuanChang1018** [mrbigmouth/acgn-stock#39]
剛剛用google帳號登入發現會顯示個人的信箱
如果可以的話,讓使用google帳號登入的人能建立一個對外顯示的ID
然後把google信箱隱藏起來

以上是個人的一點點小建議

**Comment by Costda** [comment]
希望若能抓取GOOGLE最新一次的名字,G帳號90天也只能改3次名字0.0

**Comment by mrbigmouth** [comment]
5125e620ddbd6d6695351f8f84fd30d23b3f089d
