### ISSUE TITLE
無法撒回買賣單

### ISSUE THREAD

**Issue by zozotintin** [mrbigmouth/acgn-stock#4]
![screen shot 2017-08-17 at 4 12 23 pm](https://user-images.githubusercontent.com/4221475/29402268-ec0041ea-8366-11e7-9f07-743bb5c73eb7.png)
<del>如圖所示，因為無法支付手續費所以買賣單撒不回</del>
沒事這是因為我的錢不夠…不過沒寫原因只告訴我無法支付我以為是系統出錯無法支付而不是我的錢不夠無法支付。

**Comment by zozotintin** [comment]
不好意思，這是因為我的錢不夠…請幫我刪了吧QQ

**Comment by Azraeil** [comment]
lol

**Comment by mrbigmouth** [comment]
所以你有手續費1元嗎？

**Comment by zozotintin** [comment]
後來有了，一開始沒弄明白訊息的意思而已
