### ISSUE TITLE
在股票主業面中,董事長案修改頭銜無反應

### ISSUE THREAD

**Issue by Costda** [mrbigmouth/acgn-stock#40]
RT,在股票主業面中,董事長案修改頭銜無反應,必須到股市總覽找出自己的股票才有用

話說,關於伺服器付費有著落了嗎0.0

**Comment by mrbigmouth** [comment]
剛剛兩個頁面都試過了沒發現有bug喔，
有沒有更詳細的錯誤訊息可以回報的？

付費的話，目前所有的募資平臺都是毫無下聞，可能只能走廣告路線了。

**Comment by Costda** [comment]
http://i.imgur.com/uXZRSqK.png

像在這個頁面按下去沒反應....

**Comment by Costda** [comment]
對不起,剛剛用CHROME試過,是我火狐的問題,抱歉ORZ

**Comment by mrbigmouth** [comment]
Firefox中的問題應該也修好了。
