### ISSUE TITLE
每個人登入的ip都一樣

### ISSUE THREAD

**Issue by Costda** [mrbigmouth/acgn-stock#42]
rt,目前每個人登入ip都相同,懷疑是否抓到伺服方或資料庫方的ip

**Comment by ouovouo** [comment]
要順便處理 "舉報違規紀錄"的 drm343 的IP 
現在都顯示內網IP

**Comment by Costda** [comment]
她不是自請水桶嗎?

**Comment by ouovouo** [comment]
跟自請水桶無關 我是說IP

**Comment by mrbigmouth** [comment]
這我真不知道怎麼回事啊！
程式上沒動到這裡的.....(抓IP是套件的部份)
比較可能是伺服器的問題，但兩次維修間的唯一差異只是我重開機過而已....(死)
等今天維修後重開機看看吧。

**Comment by mrbigmouth** [comment]
應該是AWS EC2網路問題，目前修好了（大概）。
