### ISSUE TITLE
[建議]查自己的持股資訊和查自己有沒有在那間公司持股應該要分開計數

### ISSUE THREAD

**Issue by softbearlolz** [mrbigmouth/acgn-stock#448]
目前兩個行為會被server視為同一類請求，滿20次就會被ban
與frozenmouse討論之後
建議將兩者分開計數

**Comment by frozenmouse** [comment]
補充說明一下
目前公司列表和公司資訊兩個頁面都會去訂閱 `queryOwnStocks`，但 rate limit 是 20/min
大概平均六秒進出一次公司頁面就會被觸發了

第一個可能的解法是提升 rate limit
這邊提到的解法是把 `queryOwnStocks` 留在公司列表和其他需要完整持股資訊的地方
公司資訊裡面只要有辦法查詢自己的持股就夠了

**Comment by frozenmouse** [comment]
在 #496 進行的過程中發現 `queryOwnStocks` 事實上在至少三處以上不同的 template 裡被訂閱
由於這屬於極度常用的資訊，因此將之改寫為全域性的訂閱
