### ISSUE TITLE
9/9更新後問題

### ISSUE THREAD

**Issue by papago89** [mrbigmouth/acgn-stock#45]
更新前新創一間公司
更新後該公司應新創成功，但疑似與先前資料長度過長無法擺放進資料庫導致的BUG類似。

2.公司使用的大小圖片改為外接連接，不用再上傳檔案也不再限制檔案大小。
    使用者可以使用imgurl等圖床放置公司圖片。
    然而在網站流量過大時，這些圖床有可能會擋掉來自系統的連結，
    因此最安全的作法應該是自己找個免費空間放置圖片。

懷疑為此項更新導致更新前新創角色上傳之圖檔資料過長，無法傳入資料庫。

**Comment by mrbigmouth** [comment]
已經處理完畢。
