### ISSUE TITLE
角色圖無法修改

### ISSUE THREAD

**Issue by ouovouo** [mrbigmouth/acgn-stock#46]
剛剛調整完之後
修改角色圖 貼URL 網址會顯示
Internal server error [500]
<img src="http://i.imgur.com/3dasb5o.png"/>

(我用無痕開的)

**Comment by ouovouo** [comment]
https://lh3.googleusercontent.com/5o1u_5QXi6GoK_YI4suBbbYYcQSmtDOxH25DBQSqyiTzAtUkchEB577R0s_8x-Xf7kvus44KdCH8dCFHe9nF-Vjnx6VOvI7kQipfHVtRQIcgDdw7_WiGyvyFf95eiT-73pnitST8or7x8Xt2KO8_Wl8K0I3qwffrLsHDufVLhdEOu1Qsdfwy5J0XLuLs3ukvVI8UIhNteMkW1Q1A63pZbzi12frOoo029IlX3gD2YgIYlpfur1tr1_S6cvTq_dtTHfsRFCwlR5Yy-asTzipWeF24kpsEqNaJqQPGo_SW1639z6zVfPt5Xg9Psemv1qkUeGDMfHUhGQQeBTtGjTrTIZ-UrT707ojWh1zmMGDwiNBjKA-pCi1Gcou-im4wgB_KnaIiMNMtJVX0BJyHlo9WppaM3xb1yq77jGdhJoyHIPrCLvGzeCaq56mayQ2Xhu7NhvJIRIblcgoOVUvhIEv9LcB11hbqL39Bgf23JifqSBiYMkpaMPZBswt8cH4Ke74iO8aWIIKJxLTVQTdwgf8iBy5CErUzLu0NOf-LBI8saQ5qu-IFzKimSBrLtLMWHZlyNlEVU0zSrU55SiFUl7k-DsugHBwwllIiNN3X4vFcMLGWZz8utlOr=s300-no

**Comment by mrbigmouth** [comment]
嗯，目前網站不接受https開頭的網址，之後會加上提示。
