### ISSUE TITLE
釋股問題?

### ISSUE THREAD

**Issue by ouovouo** [mrbigmouth/acgn-stock#47]
雖然要重置了，但我很好奇 公司為什麼沒有釋股？
高於股票參考價格的買單：126股
最後成交時間：2017/09/07 23:51:52
一天的股票總成交量：0股

股票參考價格：$ 1334
最後成交價格：$ 1334
<img src="http://i.imgur.com/sTxjwT2.png" />

請問我是中了什麼BUG?還是說因為 中間伺服器爆過 時間重算了?

**Comment by mrbigmouth** [comment]
待正式開服後再觀察

**Comment by mrbigmouth** [comment]
加上詳細log以來，看起來是有正常釋股的，還有問題請再回報。
