### ISSUE TITLE
廣告購買問題

### ISSUE THREAD

**Issue by eszerfrm** [mrbigmouth/acgn-stock#48]
已購買廣告卻不能更改廣告資訊
建議: 
1. 增加預覽功能並強制購買廣告前確認預覽程序
2. 修改廣告內容功能

**Comment by mrbigmouth** [comment]
因為其他人也可以對廣告追加投資，所以修改廣告內容功能應該不會做。

**Comment by mrbigmouth** [comment]
3eed5f7474d39d813b8cc48b693328a608e93900
