### ISSUE TITLE
新創公司可更名是否為BUG?

### ISSUE THREAD

**Issue by papago89** [mrbigmouth/acgn-stock#49]
替otis1713   push上來的
新創階段名稱可更改導致有人惡意使用此功能掛羊頭賣狗肉(掛A公司名募款,最後一刻改B公司)，ｅｘ：掛一隻低人氣角色，在上市前一刻再突襲換成其他高人氣角色藉此綁架掉目標角色。
建議:名稱一經決定就不得更改

**Comment by mrbigmouth** [comment]
63ab6d4a0bc6bbb99eee908b65c7c6f6202bd7c8

**Comment by mrbigmouth** [comment]
今晚更新
