### ISSUE TITLE
即時訊息頁面 篩選器 "交易相關" 按鈕有點問題

### ISSUE THREAD

**Issue by Azraeil** [mrbigmouth/acgn-stock#5]
如題，更新之後，篩選 "交易相關"
會把所有訊息都篩選掉
如下圖
僅篩選"交易相關"：
![image](https://user-images.githubusercontent.com/30717954/29453460-539780a4-843c-11e7-8460-8ed0001aa5bd.png)

不篩選：
![image](https://user-images.githubusercontent.com/30717954/29453451-4bcf3164-843c-11e7-94e0-95b82dec3566.png)

觸發條件是在即時訊息頁面等個*幾分鐘，
等訊息累積到一定程度[大概203筆資料]之後就會觸發的樣子

目前203 筆 或 330筆 以上都會觸發

F5重新整理 頁面之後 或是
清空就訊息就會正常

**Comment by mrbigmouth** [comment]
今晚12:00的更新會解決。
