### ISSUE TITLE
新創計畫的腳色介紹, 如果貼網址的話會出格(超出寬度)

### ISSUE THREAD

**Issue by m6fish** [mrbigmouth/acgn-stock#50]
[許願]有辦法貼超連結嗎? 
貼html <a>不安全的話, 不曉得能不能用makedown語法那樣?

`[標題](http://網址)`

**Comment by ouovouo** [comment]
<a href="https://goo.gl/">https://goo.gl/l</a>

**Comment by mrbigmouth** [comment]
這個......應該很久很久以後才會去做吧（遠目）

**Comment by silentvow** [comment]
Meteor有markdown package可以套在template上，
但markdown語法也會有XSS等安全問題。

**Comment by mrbigmouth** [comment]
b3dc64fa34621351d2c220b9c87d47541dcac606
