### ISSUE TITLE
手機版的董事會留言

### ISSUE THREAD

**Issue by vios10009** [mrbigmouth/acgn-stock#52]
如果用手機板觀看股東的留言，只會顯示第一個字。

無果手機切成網頁版，只要內容超過一定長度，剩餘的文字會顯示...而無法觀看。

**Comment by AmuletHeart** [comment]
翻轉畫面變橫的試試看

**Comment by mrbigmouth** [comment]
590c2b3b36f3e5a0dc64af735c33aef99a0535d9
