### ISSUE TITLE
npm ERR! write after end

### ISSUE THREAD

**Issue by eminfan** [mrbigmouth/acgn-stock#522]
我運行meteor npm install，
結果

![_20180724155143](https://user-images.githubusercontent.com/16729869/43124512-fa9168ec-8f59-11e8-99a1-2a3c2f5da5c0.png)

請問怎麽辦

**Comment by frozenmouse** [comment]
初步搜尋了一下，看起來和我們的程式無關，是 npm 那邊的問題
請參考 npm/npm#19989
確認一下你的 npm 版本
