### ISSUE TITLE
系統公告

### ISSUE THREAD

**Issue by konemsnq** [mrbigmouth/acgn-stock#54]
有辦法讓系統公告不在每次開啟時出現嗎
關掉後又不斷的顯示重複的訊息

**Comment by mrbigmouth** [comment]
讓所有人進網站時都會看到公告是故意的。
正常使用下，只要你不是關掉網頁重新開啟，關掉公告之後就不會再出現了才對。
如果有人的操作模式就是不斷的開新頁面，這種操作法對伺服器會產生較大的不必要負荷，能給這種人造成多一點麻煩，讓他不想繼續這樣的操作模式，那真是太好了呢。
