### ISSUE TITLE
被要求巴哈重新驗證，帳號被還原成初始狀態

### ISSUE THREAD

**Issue by shinonome05** [mrbigmouth/acgn-stock#575]
今天登入的時候被要求重新認證，原因是巴哈的手機認證過期
成功登進帳戶之後，發現所有紀錄被刪除，變成10,000元新手帳戶
帳號:(巴哈)souta20205

**Comment by frozenmouse** [comment]
這是正常狀況，每次賽季都會需要重新驗證一次股市帳號
手機認證過期並不是你的帳號被清空的原因

**Comment by shinonome05** [comment]
所以本來新的賽季一到，所以本來新的賽季一到帳號都會被清空嗎?

**Comment by frozenmouse** [comment]
是的，帳號會全部清空，重新認證之後會將你之前的操作紀錄與聖晶石等等少數可以繼承的東西繼承下來，其餘就和新帳號一樣
