### ISSUE TITLE
擁有公司股票的BUG

### ISSUE THREAD

**Issue by vios10009** [mrbigmouth/acgn-stock#58]
在「使用者的帳號資訊」網頁下，如果自己販售的股票被他人購買，「擁有公司股票」所顯示的股票數字會往上移位，造成閱讀障礙，但不會有其他影響。

**Comment by TIM756489** [comment]
(2017/09/19 13:56:52) 【創立得股】對「 日富美 公司創立計劃」的$566投資為 whatabirday 帶來了2數量的公司股票！
(2017/09/19 13:56:52) 【創立得股】對「 日富美 公司創立計劃」的$709投資為 tim756489dj 帶來了2數量的公司股票！

為什麼 709只有兩股

**Comment by vios10009** [comment]
一股256元

2017年9月19日 下午2:39，"TIM756489" <notifications@github.com>寫道：
