### ISSUE TITLE
[希望新增功能]新創計畫設定

### ISSUE THREAD

**Issue by Leolulusu** [mrbigmouth/acgn-stock#582]
創立人能在開社新創計畫後更改內容
例如:標籤   大小圖

**Comment by Leolulusu** [comment]
創立人能在開社新創計畫後更改內容
例如:標籤 大小圖

**Comment by frozenmouse** [comment]
@Leolulusu 在很久很久以前是有開放的
但因為金管會管理上的需要，避免無良經理利用新創修改的功能詐騙
所以才改成現在這樣的

如果有修改的需要的話，請聯絡金管會代勞
