### ISSUE TITLE
投資被吃掉了

### ISSUE THREAD

**Issue by sam910037** [mrbigmouth/acgn-stock#59]
投資4096給日富美創業
(2017/09/18 13:57:02) 【創立成功】 
名單內有我的名稱sam910037
卻沒拿到半張股票

**Comment by smallbomb** [comment]
+1 rockon590 QQ

**Comment by mrbigmouth** [comment]
系統將於09/19 09:46將資料回溯回09/18 09:46，新創計劃、廣告自動延期24小時。
