### ISSUE TITLE
2017/08/19更新後的新狀況

### ISSUE THREAD

**Issue by papago89** [mrbigmouth/acgn-stock#6]
公司頁面 - 選舉下個商業季度的負責經理人 董事支持率恆顯示為0 重新支持仍顯示為0
即時訊息 - 訂單完成通知似乎是會推播給所有帳號顯示
　　　　
(2017/08/19 00:39:39)  【訂單完成】您以每股$30的單價購入2數量的「桐人」公司股票的訂單已經全數交易完畢！
(2017/08/19 00:39:38)  【交易紀錄】aaaa714714以$30的單價向k03004748549購買了2數量的「桐人」公司股票！
(2017/08/19 00:39:38)  【購買下單】aaaa714714想要用每股$30的單價購買2數量的「桐人」公司股票！

**Comment by mrbigmouth** [comment]
e70cde5766aabb4aaa4cbfa4b205102cbffe8890
已修復完成。

**Comment by mrbigmouth** [comment]
該死，真的不該在剛睡醒的時候coding....晚上再修吧。

**Comment by mrbigmouth** [comment]
已修復完成。
