### ISSUE TITLE
股票售出與購買價格BUG

### ISSUE THREAD

**Issue by MurasakiNeko** [mrbigmouth/acgn-stock#61]
![image](https://user-images.githubusercontent.com/14976223/30538584-3d467062-9ca1-11e7-9806-d66066e44ff5.png)

買方開價50 賣方賣價42 理論上應該是以50賣出
系統卻顯示42賣出

**Comment by mrbigmouth** [comment]
這不是bug。
根據教學導覽：
8.股票的交易：
當有任何使用者下達任何買賣訂單時，系統會先檢視是否有價格優於或等於新訂單的訂單存在，若存在任何價格相符的訂單，則自動以「已存在的訂單價格」為準進行股票交易。直到新訂單的交易數量大於所有已存在的價格符合訂單的交易數量為止。舉例而言，若該公司存在三筆以單價10、15、20購入10股股票的訂單，此時有人下達了以單價15購入25股股票的訂單，則此訂單會先以20單價賣出10股，再15單價賣出10股，最後留下5股未交易的15單價賣出5股的訂單留在訂單列表中。在沒有任何股票成交時，股價不會有任何的變動。
