### ISSUE TITLE
編輯新創計畫的角色名稱修改無效

### ISSUE THREAD

**Issue by konata39** [mrbigmouth/acgn-stock#63]
剛剛名字不小心打錯 要修改發現不能修改

**Comment by mrbigmouth** [comment]
這是要防止之前有人假裝要上A公司，截止前一刻卻換成B公司的手段。
如果打錯名字的新創計劃不幸的上市成功了，你可以請金管會委員幫你改。
（教學導覽有金管會委員名單，或者用檢舉自己的方式？）
