### ISSUE TITLE
[建議]按需載入頁面資料

### ISSUE THREAD

**Issue by alpha4021** [mrbigmouth/acgn-stock#64]
現在玩了一天多所見，是頁面會完成所有載入之後才顯示，但明顯每個用戶對頁面上的資訊的要求都不一樣，例如我真的不需要每次都看公司的交易紀錄。
因此，我建議將頁面上不同版面的載入分割並改為按需載入，這樣可以減輕伺服器負載，也可以加快用戶頁面載入速度。

**Comment by mrbigmouth** [comment]
a818a61504033644d3d40cf995f37c2fc02d297d
f5140df7b8112e6b1d8d3acfc3ab3bba31935f0b
