### ISSUE TITLE
在產品中心的推薦票顯示有 bug

### ISSUE THREAD

**Issue by NightFeather** [mrbigmouth/acgn-stock#65]
在同頁面內第 20 項之後的產品投了推薦票之後按鈕的樣式不會變化
不過按下去會正常顯示不能重複投票的警告訊息

**Comment by NightFeather** [comment]
追加: 但是基於同公司不能投兩項產品規則的顯示變化是正常的

**Comment by mrbigmouth** [comment]
33be83de7676fc0729a61ba8a95ff3a4295a783d
