### ISSUE TITLE
股票買賣操作

### ISSUE THREAD

**Issue by alex94539** [mrbigmouth/acgn-stock#70]
![image](https://user-images.githubusercontent.com/31380333/30651594-c5ebd552-9e58-11e7-83b2-013a9e38121d.png)
會出現擁有持股，卻無法進行賣單的BUG
要打開董事會才能進行賣出動作
![image](https://user-images.githubusercontent.com/31380333/30651646-ef8abb6c-9e58-11e7-8393-cbb19518b6cd.png)

**Comment by mrbigmouth** [comment]
8d0eb5dbbfbf45799c49f3e1e26697a0f4cb4537
今晚更新
