### ISSUE TITLE
重複支持經理人的錯誤對話框出現了 User ID 而非名稱

### ISSUE THREAD

**Issue by frozenmouse** [mrbigmouth/acgn-stock#72]
在已經支持 XXGB 為八九寺真宵的經理人的情況下，再按一次支持會顯示對話框內容如下

> 使用者已經正在支持使用者3sX643LL26tSjX77m擔任「八九寺真宵」公司經理人了，無法再次進行支持！ [403]

顯示的是 XXGB 的 User ID 而非其顯示名稱

**Comment by mrbigmouth** [comment]
f7dec3be8e18c7351de855cdf44375097ad9adc8
