### ISSUE TITLE
是否能把公司改成角色?

### ISSUE THREAD

**Issue by senninl** [mrbigmouth/acgn-stock#77]
我想這樣更有愛點,因為我投資的是這個角色,而不是公司
xxx公司創立計劃 → xxx角色創立計劃
公司股票 → 角色股票

**Comment by mrbigmouth** [comment]
稍微調查了一下，也有人認為用「公司」比較有專業的感覺（？）
所以要改的話去PTT按照[章程](https://www.ptt.cc/bbs/C_Chat/M.1503647472.A.51F.html)進行討論推投吧～
