### ISSUE TITLE
無法登入 (google)

### ISSUE THREAD

**Issue by testya8592** [mrbigmouth/acgn-stock#79]
登入的時候選擇 以Google帳號登入 ，就卡在這邊沒有任何反應
![001](https://user-images.githubusercontent.com/32152789/30677817-a7157eae-9ec0-11e7-892f-f684ec19dbd9.jpg)

**Comment by wang0309** [comment]
我弟的也是這樣

**Comment by mrbigmouth** [comment]
目前有多位玩家遇到這個問題，如果你用無痕式瀏覽器可以登入的話，嘗試以下步驟可解：
1.清除瀏覽器的Local Storage（通常清Coockie、快取也會一並清除？）
2.以[https://acgn-stock.com](https://acgn-stock.com)進入網站
3.重新登入

**Comment by wang0309** [comment]
請問手機要怎麼清除Local Storage？

**Comment by wang0309** [comment]
我弟說清好了還是不行，用無痕也是一樣

**Comment by s0610188** [comment]
無法登入++ 手機電腦都是 QQ

**Comment by mrbigmouth** [comment]
目前我自己試是沒有問題的，
看遇到錯誤的使用者能不能提供瀏覽器的主控臺錯誤訊息？

**Comment by testya8592** [comment]
我使用方法 2.以https://acgn-stock.com進入網站 成功登入

**Comment by wang0309** [comment]
我弟說用方法2可以，不知道之後會不會有問題，謝謝mrbigmouth大大

**Comment by orcapen** [comment]
無法登入
無痕也不行

**Comment by orcapen** [comment]
方法二可以

**Comment by cmcmcmcm2** [comment]
沒用 都是過了 該清的都清了 該換的都換了 可是一樣 跟圖片相同

**Comment by mrbigmouth** [comment]
還不行的人, 有辦法抓瀏覽器主控台的錯誤訊息給我看嗎?

**Comment by yzyun0823** [comment]
@mrbigmouth 
貌似是http的问题
手动换成https就没有问题

**Comment by cmcmcmcm2** [comment]
怎麼之前不會這樣 PS 我手動改HTTPS:// 就正常了

**Comment by yzyun0823** [comment]
估计是和google的接口问题？

**Comment by mrbigmouth** [comment]
目前已經加了強制轉https了。
