### ISSUE TITLE
股市總覽中，在大於自己持有股票的頁數按下只列自己持有股票後的頁面顯示問題

### ISSUE THREAD

**Issue by frozenmouse** [mrbigmouth/acgn-stock#80]
點股市總覽→點最後一頁→filter 自己持有的股票
顯示內容會是自己持有的股票中的第一頁，但網址還是顯示在最後一頁

這時點進去隨便一檔股票後，按上一頁回來，就會跑到自己持有的股票的最後一頁 (= 沒東西)

**Comment by mrbigmouth** [comment]
3ec2290ab59b6f58c1b7a5883603278725c65f52
