### ISSUE TITLE
[建議][伺服器]設定HSTS Redirect

### ISSUE THREAD

**Issue by alpha4021** [mrbigmouth/acgn-stock#83]
今天早上如常登入發現GOOGLE OAUTH卡住了，來github看到#75 #76發現是需要HTTPS才能登入。
然而多數人並不會打HTTPS，或者根本沒有意識到要用HTTPS連線。
所以最簡單的方法就是設定一個Redirect，對HTTP的Request給個301然後轉跳去HTTPS。

**Comment by mrbigmouth** [comment]
已設置
