### ISSUE TITLE
產品推薦票顯示錯誤

### ISSUE THREAD

**Issue by alex94539** [mrbigmouth/acgn-stock#84]
![image](https://user-images.githubusercontent.com/31380333/30682163-0edfaa40-9edb-11e7-8697-767465dd4fd9.png)
在產品中心觀看會出現問題

**Comment by silentvow** [comment]
這個是因為投過的公司不能再投所以把按鈕拔掉的關係，
我覺得換成disable風格的按鈕可能會比較好。

**Comment by mrbigmouth** [comment]
371f78ec8279af1e287308a13f6a18591a515387
