### ISSUE TITLE
載入過久且網頁會跑掉

### ISSUE THREAD

**Issue by h1431532403240** [mrbigmouth/acgn-stock#88]
如題，網頁有時會一直卡在載入畫面，不然就是畫面比例整個跑掉，想問一下是我瀏覽器的問題，還是伺服器那邊的問題QQ

https://i.imgur.com/0BGhrBe.jpg

**Comment by silentvow** [comment]
清流覽器快取，改用 https://acgn-stock.com 連看看?

**Comment by mrbigmouth** [comment]
早上的時候想辦法讓連進去的人會被程式自動清快取了，再試看看吧。
