### ISSUE TITLE
暱稱問題

### ISSUE THREAD

**Issue by YekaterinaG** [mrbigmouth/acgn-stock#93]
目前小弟使用GMAIL登入，但在系統中顯示的是真名，想請問能否有風王結界可以幫忙隱藏名子。

感謝。

**Comment by mrbigmouth** [comment]
可以直接改Gmail名稱，或者直接撤銷Google對acgn-stock.com的授權，程式在抓不到你的名稱時會改抓Email帳號做為顯示。
