### ISSUE TITLE
新創公司被查封後投資者的錢會不會退回?

### ISSUE THREAD

**Issue by write3** [mrbigmouth/acgn-stock#99]
投資者血本無歸

**Comment by supmiku39** [comment]
請參考金管會規則：https://docs.google.com/document/d/1INBDMg1MFOcEucdJDO57qIkTsFR7iNiZpC2JW2qoYso/edit
「＊無論是因何種理由BAN掉的公司，投資人的錢都不會歸還，請投資前看清楚，好好想過後再投。」
只能說現在騙子很多，在投新創之前需要多多注意，先確定好該公司是否符合金管會規則再進行投資，以免血本無歸
